import { ImageSourcePropType } from 'react-native';

/**
 * image_key (from exercise_defs) -> bundled illustration.
 * GENERATED from the contents of assets/exercises/ — regenerate with
 * scripts/gen_image_map.js after adding art. Keys missing here (new
 * catalog art not yet generated, custom exercises) fall back to a
 * muscle-group icon tile in the picker.
 */
export const EXERCISE_IMAGES: Record<string, ImageSourcePropType> = {
  'ab-wheel-rollout': require('../../assets/exercises/ab-wheel-rollout.png'),
  'arnold-press': require('../../assets/exercises/arnold-press.webp'),
  'back-extension': require('../../assets/exercises/back-extension.webp'),
  'barbell-curl': require('../../assets/exercises/barbell-curl.webp'),
  'barbell-row': require('../../assets/exercises/barbell-row.webp'),
  'barbell-shrug': require('../../assets/exercises/barbell-shrug.png'),
  'bench-press': require('../../assets/exercises/bench-press.webp'),
  'bicycle-crunch': require('../../assets/exercises/bicycle-crunch.png'),
  'bulgarian-split-squat': require('../../assets/exercises/bulgarian-split-squat.png'),
  'cable-crossover': require('../../assets/exercises/cable-crossover.webp'),
  'cable-crunch': require('../../assets/exercises/cable-crunch.png'),
  'cable-curl': require('../../assets/exercises/cable-curl.webp'),
  'cable-hammer-curl': require('../../assets/exercises/cable-hammer-curl.png'),
  'cable-lateral-raise': require('../../assets/exercises/cable-lateral-raise.png'),
  'cable-overhead-extension': require('../../assets/exercises/cable-overhead-extension.webp'),
  'calf-raise': require('../../assets/exercises/calf-raise.webp'),
  'chest-fly': require('../../assets/exercises/chest-fly.webp'),
  'chin-ups': require('../../assets/exercises/chin-ups.webp'),
  'close-grip-bench-press': require('../../assets/exercises/close-grip-bench-press.webp'),
  'concentration-curl': require('../../assets/exercises/concentration-curl.webp'),
  'crunch': require('../../assets/exercises/crunch.png'),
  'dead-bug': require('../../assets/exercises/dead-bug.png'),
  'deadlift': require('../../assets/exercises/deadlift.webp'),
  'decline-bench-press': require('../../assets/exercises/decline-bench-press.png'),
  'decline-sit-up': require('../../assets/exercises/decline-sit-up.png'),
  'diamond-push-ups': require('../../assets/exercises/diamond-push-ups.webp'),
  'dips': require('../../assets/exercises/dips.webp'),
  'dumbbell-bench-press': require('../../assets/exercises/dumbbell-bench-press.webp'),
  'dumbbell-curl': require('../../assets/exercises/dumbbell-curl.webp'),
  'dumbbell-kickback': require('../../assets/exercises/dumbbell-kickback.webp'),
  'dumbbell-row': require('../../assets/exercises/dumbbell-row.webp'),
  'dumbbell-shoulder-press': require('../../assets/exercises/dumbbell-shoulder-press.webp'),
  'ez-bar-curl': require('../../assets/exercises/ez-bar-curl.png'),
  'face-pull': require('../../assets/exercises/face-pull.webp'),
  'farmers-carry': require('../../assets/exercises/farmers-carry.png'),
  'front-raise': require('../../assets/exercises/front-raise.webp'),
  'front-squat': require('../../assets/exercises/front-squat.png'),
  'glute-bridge': require('../../assets/exercises/glute-bridge.png'),
  'goblet-squat': require('../../assets/exercises/goblet-squat.png'),
  'good-morning': require('../../assets/exercises/good-morning.png'),
  'hack-squat': require('../../assets/exercises/hack-squat.png'),
  'hammer-curl': require('../../assets/exercises/hammer-curl.webp'),
  'hanging-knee-raise': require('../../assets/exercises/hanging-knee-raise.png'),
  'hanging-leg-raise': require('../../assets/exercises/hanging-leg-raise.png'),
  'hip-abduction': require('../../assets/exercises/hip-abduction.png'),
  'hip-thrust': require('../../assets/exercises/hip-thrust.webp'),
  'hollow-hold': require('../../assets/exercises/hollow-hold.png'),
  'incline-bench-press': require('../../assets/exercises/incline-bench-press.webp'),
  'incline-dumbbell-curl': require('../../assets/exercises/incline-dumbbell-curl.webp'),
  'incline-dumbbell-press': require('../../assets/exercises/incline-dumbbell-press.webp'),
  'lat-pulldown': require('../../assets/exercises/lat-pulldown.webp'),
  'lateral-raise': require('../../assets/exercises/lateral-raise.webp'),
  'leg-curl': require('../../assets/exercises/leg-curl.webp'),
  'leg-extension': require('../../assets/exercises/leg-extension.webp'),
  'leg-press': require('../../assets/exercises/leg-press.webp'),
  'lunges': require('../../assets/exercises/lunges.webp'),
  'machine-chest-press': require('../../assets/exercises/machine-chest-press.png'),
  'machine-row': require('../../assets/exercises/machine-row.png'),
  'machine-shoulder-press': require('../../assets/exercises/machine-shoulder-press.png'),
  'machine-tricep-extension': require('../../assets/exercises/machine-tricep-extension.png'),
  'mountain-climbers': require('../../assets/exercises/mountain-climbers.png'),
  'neutral-grip-pull-ups': require('../../assets/exercises/neutral-grip-pull-ups.png'),
  'overhead-press': require('../../assets/exercises/overhead-press.webp'),
  'overhead-tricep-extension': require('../../assets/exercises/overhead-tricep-extension.webp'),
  'pallof-press': require('../../assets/exercises/pallof-press.png'),
  'pec-deck': require('../../assets/exercises/pec-deck.png'),
  'plank': require('../../assets/exercises/plank.png'),
  'preacher-curl': require('../../assets/exercises/preacher-curl.webp'),
  'pull-ups': require('../../assets/exercises/pull-ups.webp'),
  'push-press': require('../../assets/exercises/push-press.png'),
  'push-ups': require('../../assets/exercises/push-ups.webp'),
  'rear-delt-fly': require('../../assets/exercises/rear-delt-fly.webp'),
  'romanian-deadlift': require('../../assets/exercises/romanian-deadlift.webp'),
  'russian-twist': require('../../assets/exercises/russian-twist.png'),
  'seated-cable-row': require('../../assets/exercises/seated-cable-row.webp'),
  'seated-calf-raise': require('../../assets/exercises/seated-calf-raise.png'),
  'side-plank': require('../../assets/exercises/side-plank.png'),
  'skull-crushers': require('../../assets/exercises/skull-crushers.webp'),
  'squat': require('../../assets/exercises/squat.webp'),
  'step-ups': require('../../assets/exercises/step-ups.png'),
  'sumo-deadlift': require('../../assets/exercises/sumo-deadlift.png'),
  't-bar-row': require('../../assets/exercises/t-bar-row.webp'),
  'tricep-dips': require('../../assets/exercises/tricep-dips.webp'),
  'tricep-pushdown': require('../../assets/exercises/tricep-pushdown.webp'),
  'upright-row': require('../../assets/exercises/upright-row.webp'),
  'v-ups': require('../../assets/exercises/v-ups.png'),
  'walking-lunges': require('../../assets/exercises/walking-lunges.png'),
  'woodchopper': require('../../assets/exercises/woodchopper.png'),
};
